---
version: '3.5'

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6380'
    command: |-
      redis-server
      --save 20 1
      --loglevel warning
      --port 6380
      --requirepass redispassword
